### ISSUE TITLE
CONTRIBUTING.md page not found

### ISSUE THREAD

**Issue by sajibAdhi** [laraflow/form#36]

**Comment by hafijul233** [comment]
Can you contribute a layout design for the page?

**Comment by sajibAdhi** [comment]
> @sajibAdhi Can you contribute a layout design for the page? As a reference repo link is https://github.com/mah-shamim/city-bank-api.git ![Firefox_Screenshot_2022-10-02T08-31-23 225Z](https://user-images.githubusercontent.com/24684511/193445393-d8364ad7-0fab-44ec-a604-a88503618f10.png)

Bro I can't find the any contributing.md file in there referenced repo.
I will try to make a simple CONIBUTNG.md.

**Comment by sajibAdhi** [comment]
Brother add another label "hacktoberfest-accepted" on this issue.

**Comment by hafijul233** [comment]
@sajibAdhi you may need to create the contribution.md file inside the docs directory. not on root directory it will render the github page from there

**Comment by sajibAdhi** [comment]
@hafijul233 In PR # 37, I included a docs/contributing.md file.
